### ISSUE TITLE
Launch URL in Incognito, opens new window instead of tab

### ISSUE THREAD

**Issue by Bobz-zg** [strongbox-password-safe/browser-autofill#10]
When using search in extenstion and when I press 'Launch URL', new browser window is opened.
I'm in incognito mode and I would prefer to just opena a new tab.
This happens only if I'm in incognito window. 

Google Chrome OSX
Version 121.0.6167.184 (Official Build) (x86_64)

**Comment by strongbox-mark** [comment]
Hi @Bobz-zg - thanks for the suggestion. As a quick guess I would say this is default Chrome behaviour in incognito mode, perhaps it's a requirement, for security/privacy reasons. Do you happen to know if that's the case?

**Comment by Bobz-zg** [comment]
Hm, thougt it's a bug.
Yandex browser incognito (also Chromium based) and Firefox private are opening new tab, unlike Google Chrome

**Comment by strongbox-mark** [comment]
Hi @Bobz-zg - This should be fixed for you I believe with 1.2.0

**Comment by Bobz-zg** [comment]
Confirming it works, thanks Mark!
