### ISSUE TITLE
Add light/dark/system mode toggle

### ISSUE THREAD

**Issue by czottmann** [strongbox-password-safe/browser-autofill#2]
Extension v1.0.6
Brave Browser v1.50.121 (Chromium: 112.0.5615.138)
macOS 13.3.1

I like the Chrome extension so far, but would it be possible to add a switch for dark/light/automatic mode, please? During the day I use light mode, and the extension overlays stick out like a sore thumb. ;)

Maybe there is one and I just can't find it?

Thanks!

**Comment by strongbox-mark** [comment]
Hi @czottmann - You can now choose light or dark from the Settings screen as of 1.0.12
