### ISSUE TITLE
Add font size settings

### ISSUE THREAD

**Issue by czottmann** [strongbox-password-safe/browser-autofill#3]
Extension v1.0.6
Brave Browser v1.50.121 (Chromium: 112.0.5615.138)
macOS 13.3.1

The extension works fine but size-wise, it's a bit much IMHO. If there was a way to adjust the font size (even just a relatively simple "Font size: s/m/l/xl" switch), that'd go a long way.

**Comment by sammcj** [comment]
Yeah it seems really small - but also like it's not properly anti-aliased, perhaps there's something about it that's preventing hinting and as such making it blurred 🤔.

Firefox 114
macOS 13.4

![image](https://github.com/strongbox-password-safe/browser-autofill/assets/862951/c4983d51-439e-4a3e-af9f-631ba160479e)

**Comment by strongbox-mark** [comment]
You can now set the font size for the plugin from the popup settings screen as of 1.0.12

**Comment by sammcj** [comment]
Legend, thanks!

**Comment by czottmann** [comment]
Thanks @strongbox-mark!
