### ISSUE TITLE
Autofill shortcut / hotkey setting

### ISSUE THREAD

**Issue by sammcj** [strongbox-password-safe/browser-autofill#4]
I can find where to get / set the shortcut/hotkey to trigger an autofill and (re-)copy the TOPT to the clipboard.

With 1PW this defaulted to `cmd` + `.` and I believe with BitWarden it's `cmd`+`shift`+`l`.

At present I'm working around it back clicking on the Strongbox icon under addons every time but this is a bit painful.

![image](https://github.com/strongbox-password-safe/browser-autofill/assets/862951/2a6dd614-bad3-4b19-b55c-344377e07678)

**Comment by strongbox-mark** [comment]
The default is Cmd+Shift+L but this is configurable in your browser. e.g. on Chrome it's at: chrome://extensions/shortcuts and on Firefox you can find them using this: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by sammcj** [comment]
Wow! In the 15~ years I've used Firefox I can't believe that I hadn't stumbled across that extensions shortcuts menu 🤣 

Thanks Mark - sorry to waste your time with this one!
