### ISSUE TITLE
Selecting the TOPT code does not perform a fill or copy to clipboard

### ISSUE THREAD

**Issue by sammcj** [strongbox-password-safe/browser-autofill#5]
When clicking the Strongbox icon and selecting the TOPT code nothing happens.

I would have expected it to auto-fill the code on the current page and copy the TOPT code to the clipboard.

![image](https://github.com/strongbox-password-safe/browser-autofill/assets/862951/f67ea773-ef0c-4e3f-977c-3468296d8b41)

**Comment by strongbox-mark** [comment]
If you click on the little "Timer" icon just above right you'll get the code copied but not a bad idea to also be able to click on the code itself. Note that the code is also copied to the clipboard when you do a fill, so no need to go hunting for this in most cases. Just hit "Paste".

**Comment by sammcj** [comment]
Ahh I see, yeah the timer icon does copy it. Those icons (and really the whole Strongbox extension pop-up) are _really_ small by the way (screenshot below).

Note - with the clipboard I've got it to clear passwords after 20 seconds which seems to clear the TOPT codes as well.

![image](https://github.com/strongbox-password-safe/browser-autofill/assets/862951/7bd3e1e3-e286-4b23-bc01-4aed8af2421b)

**Comment by strongbox-mark** [comment]
That's a good point about the Clipboard clearing the TOTP, it doesn't really need to, since the code expires itself. Will add that to the backlog.

**Comment by strongbox-mark** [comment]
@sammcj You should now be able to click on the TOTP code to copy, let me know if that's not the case!

**Comment by sammcj** [comment]
Excellent! Thank you Mark!
