### ISSUE TITLE
[Firefox extension] UI glitches in website dark mode

### ISSUE THREAD

**Issue by emikaadeo-git** [strongbox-password-safe/browser-autofill#8]
I think the screenshots will demonstrate better what the issue is.
Website [https://github.com/login](url)
Firefox: 118.0.2
Strongbox extension: 1.0.12

This is how the login page looks when is in light mode
<img width="324" alt="light" src="https://github.com/strongbox-password-safe/browser-autofill/assets/56483380/39364279-988a-4f41-acfb-36fccccf39e3">

This is how the login page looks when is in dark mode
<img width="324" alt="dark" src="https://github.com/strongbox-password-safe/browser-autofill/assets/56483380/4b7f666d-4873-4f60-80fa-9237706ea58b">

**Comment by strongbox-mark** [comment]
I assume you are talking about the white border surrounding the inline menu?

This should be fixed for you in the latest 1.0.12 which you indicate that you have already installed. We're not seeing that on this side, could you try removing the extension, restarting Chrome and re-adding the extension? Could be you're seeing some kind of caching issue.

**Comment by strongbox-mark** [comment]
Got it, yeah, seeing the same. We'll get that fixed.

**Comment by strongbox-mark** [comment]
This should be fixed for you @emikaadeo-git with 1.0.13 - Could you check and close?
