### ISSUE TITLE
[BUG][Chrome] Custom field with more than 1024 characters 

### ISSUE THREAD

**Issue by mietzen** [strongbox-password-safe/browser-autofill#9]
I added a custom field to an entry with more than 1024 characters, when copying it via the auto-fill extension (chrome) it is cut after 1024 characters. 

I this a known limitation?

**Comment by strongbox-mark** [comment]
We do have a limit in there, but we might be a little too conservative, what is the size of your field? and can I ask the use case  behind this large field? So I can get some context.

**Comment by mietzen** [comment]
It is my alternate solution for: https://github.com/strongbox-password-safe/Strongbox/issues/764
I guess this would even be better, since I could copy the value directly from the Browser.
But to my specific use case:
I use the [create-github-app-token](https://github.com/actions/create-github-app-token) action to generate one time and fine grained github access tokens. I use these tokens to e.g. auto merge a pull request from dependabot or automatically create a new release. 
To create these tokens you have to create a GitHub App and handover it's `app-id` and `private-key` to `create-github-app-token`.

I like to create different GitHub Apps for different scopes, e.g. one app that can only merge, one that can only create a release, etc. 
Everytime I create a new repo that uses one of these apps I need to add the ID and key as repo secret in GitHub.
I started to save the IDs and keys as custom field to the GitHub entry inside strongbox, so I can easily access them and copy/paste them when creating a new repo.

The key is a RSA private key with a length of 1679 characters:

```
$ cat app-key.pem | wc -m
    1679
```

But I don't know if this could change in the future.

**Comment by strongbox-mark** [comment]
Right, interesting, we'll increase the limit significantly in the next release, so this won't be an issue for you any more.

**Comment by strongbox-mark** [comment]
Hi @mietzen - This should be improved for you now in 1.59.4. Feel free to reopen if it's not doing what you want.
